; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Mon Mar 16 2020 12:51:03 GMT-0600 (Mountain Daylight Time)
; hand edited and tested June 16 2020
G91               ; relative positioning
G1 H1 X-310 F2000 ; move quickly to X axis endstop and stop there (first pass)
G1 H0 X3 F2000    ; go back a few mm
G1 H1 X-6 F100  ; move slowly to X axis endstop once more (second pass)
G90               ; absolute positioning

