; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Mon Mar 16 2020 12:51:03 GMT-0600 (Mountain Daylight Time)
; hand edited and tested March 27
G91               ; relative positioning
G1 H1 Y-251 F2000 ; move quickly to Y axis endstop and stop there (first pass)
G1 H0 Y5 F2000    ; go back a few mm
G1 H1 Y-6 F360  ; move slowly to X axis endstop once more (second pass)
G90               ; absolute positioning

