; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Mon Mar 16 2020 12:51:04 GMT-0600 (Mountain Daylight Time)
M118 S"Running pause.g"
M83            ; relative extruder moves
G1 E-1 F3600   ; retract 1mm of filament
G91            ; relative positioning
G1 Z5 F360     ; lift Z by 5mm
G90            ; absolute positioning
M118 S"Finished pause.g"

