; tpost1.g
; called after tool 1 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Mon Mar 16 2020 12:51:05 GMT-0600 (Mountain Daylight Time)
; Wait for set temperatures to be reached
M116 P1

